language: java

git:
  depth: 1
  
cache:
  directories:
  - $HOME/.m2
  
script:
- mvn clean install

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  draft: true
  on:
    repo: https://github.com/rbudde/miniserver
    tags: true